services:
  node-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "15173:5173"
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}